version: "3"

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command:
      [
        "--cassandra.keyspace=jaeger_v1_dc1",
        "--cassandra.servers=cassandra",
        "--collector.zipkin.http-port=9411",
      ]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: always
    depends_on:
      - cassandra-schema
  
  jaeger-query:
    image: jaegertracing/jaeger-query
    command:
      ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    ports:
      - "16686:16686"
      - "16687"
    restart: always
    depends_on:
      - cassandra-schema
  
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: always
    depends_on:
      - jaeger-collector
  
  cassandra:
    image: cassandra:3.9
  
  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    restart: always
    depends_on:
      - cassandra


  mssql:
    image: mcr.microsoft.com/mssql/server    
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
      - MSSQL_PID=Developer

  create-db-sql:
    image: mcr.microsoft.com/mssql-tools    
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password@123" -Q "create database [db-sql-hello-word]"; do sleep 5; done'

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"


  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=3
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    ports:
      - "9092:9092"


  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine
    ports:
      - "22:22"
    command: sftpuser:Password@123:::upload

  sftp_ssh:
    container_name: sftp_ssh
    image: atmoz/sftp:alpine
    volumes:
      - ./sftp-ssh/id_rsa.pub:/home/sftpuser/.ssh/keys/id_rsa.pub:ro
    ports:
      - "2222:22"
    command: sftpuser::1001::upload